spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/photo_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
alipay:
  appId: 9021000138671790
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCs5ug5x3Hk0+GeczGyiXP0gmpTrU2v3q9rBKGzs6PoISOuKTRKpnz2KwDw/9iHyUDyKqQO4vuVOOoWQ/XwT+xKC+f2ciDCnIfHCN4o7XmH5O+wtnnTvVxcjxgVJcx9fQYcKIrj1NwKGOhJg7v54tB3CU38bMRVB05NDSSWzS/QfBqG20qpX0b4QHXc36nKZ/GV70NNXdgXzuJTP5dtAlFjzIa2Rqrj41jfNINH6ahKcwqTtl7HlGH9Zmv9yuMc/8RYIx1naCY9gcRSByVdjuDa1vE8jhBBBXZ96TFb24I6mFM48+8y5oVu2FQzfpQsyMt4XT4+HN5VlxfgS2L3am8pAgMBAAECggEAGcvxxf0d3xhFx1BEj/C2Hjr/BjELMDw3S+5K+fbJc67OFgQLyz9/0XKlF0/0zH2YdQkrpRT0mFT/iAbnwM0L4hhYqYppnN+h2m5WRyD3SvE7WdA/6PmNuDmZTD5xfh+TM8xQvKFbmx4QOjevah8PH1OCETFhMZZ/djuJw/4lLiO2kP6nfpA8JzQJ2QxGNfuaM9ch44h3wLcmlqUvcSZutcMBUoRBztibjgd2Lg2tbZqMqQdo6VH/gPAswX9nPT7kjBq+zAbczaMxEhlv9vKPQLWk0ZYIkCSat1WHOlmSdYCEadv/FQn6gdyKm5ATaZgn6jAtls5TADeSFDy3XjlNAQKBgQD0AAJMHl/rEDC6EnLYhjQZ4U22lNFB88O1KBj3s0oz8qxjVycdWVdnlDRpJEzv6YlpmCIIkBbdFeP5Aws3m0yxZi04yhLD7wgJrZmAYdCzN/eHMf3Iui65ROEtDFsnvirkdlNnPCa6MFDq4iUJdKU0LLSyPBFuS6EzC7GbG74V+QKBgQC1Z8PGU4AZeSccr2chHMdKV3F88T+UfJCdOsLENptfJtSnzwhmcy6fRtZPt/Vvj6xAzdAVekfuSRG4hn/6WPVD+4+11a83WzMgPnce0hncEx1EQXgwU1YCf/ndQFkCEfL1iAXT6ieJKsLHM27T7j2gw55KKaIJf8LVLducUf6usQKBgQDsYfHX0nl0XfwG2AahE+r3w5kpMCVGMqVAJLeDiRNzHj+6Ad3oBfyyYRchYUSUDHjObs9R4l30E9gHDtbYKUD0gBuBb+scHL95uNAEWz730VmhhWHrC8xmOn+3x8erygT9zlBgrBqMuHA8DZh5/6Jo2IK6RY1RgD2MGWEX9pmB6QKBgQCwdBKW47oDDTniSSvDpb6krZISuofh45i3l+TD/2n6kEbiRBwjq356J+lm+cWfkt022/vAKIW3XxQBrbLmzYkla5lKgmRBMFD22Ev+itfkniMltZk3SJitLdbaRDFQNi1ib8FbdLSoVBPKuFjhhSglLKLX+M9I9iGKQ2UPFSLqwQKBgFGnboD6F+OTLZ7yBFbqDbuBh60/X84+p9bnl/DSfQbfUPyT5vpt+VoeERg/fl8abS93AMvyUcyWF9y+Lv5FxNi2i6Dg+Pw/zlmBSs11JGFEb0wW0jowkXvyUNM/TNORrEnIaLCdcEZ5k8dPK9MHTchOBZpI0+lBwOGrtims55un
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArOboOcdx5NPhnnMxsolz9IJqU61Nr96vawShs7Oj6CEjrik0SqZ89isA8P/Yh8lA8iqkDuL7lTjqFkP18E/sSgvn9nIgwpyHxwjeKO15h+TvsLZ5071cXI8YFSXMfX0GHCiK49TcChjoSYO7+eLQdwlN/GzEVQdOTQ0kls0v0HwahttKqV9G+EB13N+pymfxle9DTV3YF87iUz+XbQJRY8yGtkaq4+NY3zSDR+moSnMKk7Zex5Rh/WZr/crjHP/EWCMdZ2gmPYHEUgclXY7g2tbxPI4QQQV2fekxW9uCOphTOPPvMuaFbthUM36ULMjLeF0+PhzeVZcX4Eti92pvKQIDAQAB
  notifyUrl: http://localhost:10086/alipay/notify

#  notifyUrl: http://xxx/alipay/notify
logging:
  level:
    com.zhiend.netflix: info
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  type-aliases-package: com.zhiend.photo.entity
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
# 将表名 order 用反引号包裹起来
mybatis-plus.global-config.db-config.table-underline: true
server:
  port: 10086

# 上传文件存储目录
upload:
  dir: src/main/resources/static/photo

knife4j:
  enable: true
  openapi:
    title: 学生管理接口文档
    description: "学生管理接口文档"
    email: sse_d@qq.com
    concat: zhiend
    url: http://localhost:10086/doc.html
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.zhiend.photo.controller
